### ISSUE TITLE
Doesn't work well with cloudera Impala jdbc driver when the table has decimal fields

### ISSUE THREAD

**Issue by rajiv-shringi-A1** [codingtony/docker-impala#2]
I am trying to use the ImpalaJDBC4-2.5.5.jar on top of codingtony/docker-impala image to query data from the impala container in my java application. It works fine for the most part, but if the table has decimal fields, the driver throws a null pointer exception.

example table:

CREATE TABLE transaction
(
ID string,
Total DECIMAL 
);

Impala jdbc driver throws a null pointer when trying to read the table metadata, and then throws "TABLE NOT FOUND" exception. If i remove the decimal field or change the data type to int, then the code works fine.

The driver unfortunately is not open source, and as such I cannot debug efficiently without the source:
http://www.cloudera.com/content/www/en-us/downloads/connectors/impala/jdbc/2-5-5.html

Not sure if this would be a bug on the driver or on the image.

**Comment by codingtony** [comment]
Have you tried using impala-shell ?

**Comment by rajiv-shringi-A1** [comment]
Yes, the same query works fine in Impala-shell. So I guess this is a bug on the driver itself or just due to a version mismatch between the docker impala container and the driver. I am using Impala JDBC driver version 2.5.5. 

Can you update the image to the latest CDH5 2.x distribution? This is because, even if I use the latest hive driver (hive-jdbc v1.2.1), and try to issue the same query - I get the error > 

Caused by: org.apache.hive.service.cli.HiveSQLException: Ignoring invalid configuration option: use:database
    at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:256)
    at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:247)
    at org.apache.hive.jdbc.HiveConnection.openSession(HiveConnection.java:586)
    at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:192)
    at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)

And if I run the same query using the same hive driver against a CDH 2.2.0-cdh5.4.7 impala installation in our dev environment, it works fine.

**Comment by rajiv-shringi-A1** [comment]
I think you just need to build and push the latest image to the docker repo. When I take your docker file and build the image, I see the Impala version as 2.x.

Closing this.

**Comment by codingtony** [comment]
I believe that if you rebuild the image, it will probably take the latest
impala release.

Can you check the version output of  impala-shell ?
Out of curiosity, which driver you are trying to use ?

-tony

**Comment by SunjanaK** [comment]
Hi @rajiv-shringi-A1 
Would you mind sharing how you managed to get JDBC connected to docker Impala? I've been struggling with that for a few days. 

Thank you so much!
